production:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/blacklight
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/blacklight
    pid_dir: '/var/run'

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/blacklight
    pid_dir: '/var/run'
