#server {
#
#  if ($ua_redirect) {
#    return 444;
#  }
#
#  deny 23.22.35.162;
#  deny 3.224.220.101;
#  deny 52.70.240.171;
#
#  listen 80 default_server;
#  server_name SITE_DOMAINS;
#  return 301 https://$host$request_uri;
#}

server {

  if ($ua_redirect) {
    return 444;
  }

  listen 80;
  server_name SITE_DOMAINS;
  root /var/www/rails/public;

  client_max_body_size 2m;

   deny 23.22.35.162;
   deny 3.224.220.101;
   deny 52.70.240.171;
 
  passenger_enabled on;
  passenger_user app;

  passenger_ruby /usr/bin/ruby;
}

